### ISSUE TITLE
Compatibility Phoenix & Ecto

### ISSUE THREAD

**Issue by UnderFenex** [lukaszsamson/telemetry_metrics_zabbix#2] opened 2020-11-14 18:13 UTC
Hi, in this article https://elixirschool.com/blog/instrumenting_phoenix_with_telemetry_part_three/, there is a reference by default telemtry values collected from phoenix. 

I'm using phoenix as an api endpoint.

In the example, they use:
```
      {TelemetryMetricsStatsd, metrics: metrics(), formatter: :datadog} # Add the formatter here!

``` 

And the metric:

```
    summary(
      "phoenix.router_dispatch.stop.duration",
      unit: {:native, :millisecond},
      tags: [:plug, :plug_opts]
    ),
```

And running the api call, I get this error:

```
[error] Elixir.TelemetryMetricsZabbix: could not format metric %Telemetry.Metrics.Summary{description: nil, event_name: [:phoenix, :router_dispatch, :stop], keep: nil, measurement: #Function<4.70336728/1 in Telemetry.Metrics.maybe_convert_measurement/2>, name: [:phoenix, :router_dispatch, :stop, :duration], reporter_options: [], tag_values: #Function<0.70336728/1 in Telemetry.Metrics.default_metric_options/0>, tags: [:plug, :plug_opts], unit: :millisecond}
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[schema: TestWeb.Schema, socket: TestWeb.UserSocket]
```

Any ideas, in how to handle this list?

**Comment by lukaszsamson** [comment] 2020-11-14 20:06
Please post a project or a test case that reproduces this error. Here are some examples https://github.com/lukaszsamson/telemetry_metrics_zabbix/blob/master/test/telemetry_metrics_zabbix_test.exs
In your log the error is from a `counter` metric `phoenix.router_dispatch.stop.count` not a `summary` `phoenix.router_dispatch.stop.duration`

**Comment by UnderFenex** [comment] 2020-11-15 00:33
Sorry, I updated, both summary and counter from phoenix default vaules show error.

I'm not sure how to log what are the values that are being displayed, I assume that are these?:

[schema: TestWeb.Schema, socket: TestWeb.UserSocket]

**Comment by lukaszsamson** [comment] 2020-11-15 08:53
Sorry, I can't reproduce this error in a sample phoenix app with the metric you provided. Where is the crash coming from? You didn't post the stacktrace.

Please create and share a repo/test that reproduces it, otherwise I won't be able to help you.

BTW
`formatter: :datadog` is not a valid option for this library

**Comment by UnderFenex** [comment] 2020-11-15 15:32
Hi, I seems that the stop directive also includes the start directive. Here it's the Phoenix Log:

```
defmodule TelemetryMetricsZabbixTest do
  use ExUnit.Case, async: false
  doctest TelemetryMetricsZabbix
  import Telemetry.Metrics
  import Mock
  import ExUnit.CaptureLog

  test "phoenix router dispatch" do
    metrics = [
      summary("phoenix.router_dispatch.stop.duration", unit: {:native, :millisecond}, tags: [:plug, :plug_opts]),
    ]

    assert {:ok, pid} = TelemetryMetricsZabbix.start_link(metrics: metrics)
    assert [
      %{
        config: :ok,
        event_name: [:phoenix, :router_dispatch, :start],
        id: {Phoenix.Logger, [:phoenix, :router_dispatch, :start]}
      },
      %{
        config: [
          %Telemetry.Metrics.Summary{
            description: nil, 
            event_name: [:phoenix, :router_dispatch, :stop], 
            keep: nil,
            name: [:phoenix, :router_dispatch, :stop, :duration],
            reporter_options: [],
            tags: [:plug, :plug_opts],
            unit: :millisecond
          }
        ]
      }
    ] = :telemetry.list_handlers([:phoenix, :router_dispatch])
  end
end
```

**Comment by lukaszsamson** [comment] 2020-11-15 15:53
Please post a bug repro if this is an error. Use elixirforums or stackoverflow for support

**Comment by UnderFenex** [comment] 2020-11-15 16:03
I don't think this is an error, this is the default report for this measurement. I think this can be a enhance for this library. Thnx!

**Comment by lukaszsamson** [comment] 2020-11-15 16:06
If you have an idea how to improve it then go ahead and submit a PR. I'm going to close this issue then.

**Closed as completed by lukaszsamson** 2020-11-15 16:06 UTC
